# Generated by Django 5.0.1 on 2024-01-20 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_customer_gstin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gstin',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='gstin',
            name='number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gstin',
        ),
        migrations.AddField(
            model_name='gstin',
            name='gstin_number',
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='gstin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
