# Generated by Django 5.0.1 on 2024-01-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_gstin_customer_remove_gstin_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
