# Generated by Django 5.0.1 on 2024-01-20 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gstin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.gstin'),
        ),
    ]
